project:
  type: website
  output-dir: docs

website:
  title: "Sarah Martinson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: MLIS Portfolio
      - href: professional-work.qmd
        text: Professional Work
      - href: graduate-studies.qmd
        text: Graduate Studies
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual
